language: c
sudo: false

cache:
  directories:
    - $HOME/cache

addons: {apt: {packages: [yasm]}}

before_script:
#  - export TOXCORE_REPO=TokTok/toxcore
  - export TOXCORE_REPO=irungentoo/toxcore
  - export CACHE_DIR="$HOME/cache"
  - export CFLAGS="-I$CACHE_DIR/usr/include"
  - export LDFLAGS="-L$CACHE_DIR/usr/lib"
  - export LD_LIBRARY_PATH="$CACHE_DIR/usr/lib"
  - export PKG_CONFIG_PATH="$CACHE_DIR/usr/lib/pkgconfig"
  - tools/install-deps.sh > /dev/null

script:
  - make
